NonPrefix Thread  Command
SCE-Development/SCE-discord-bot pull request #113
Opened 2020-12-19 21:03 UTC by lupatrick13

- 

1.  Able to create threads using an input ID
2. Add message using a thread ID search (Regex)
3.  If there are multiple thread results, user can look at a list of threads and rechoose an ID by typing it in

2020-12-22 00:13 UTC, jerrylee17 commented
`npm run lint`

Also rebase patrick branch (it's 2 commits behind master)

2020-12-24 04:09 UTC, charlotte-zhuang requested changes
I made a few comments.

1. Documentation comment changes
2. Add example field to command
3. Don't paginate threads if they fit on one page
3. Wrap around on paginated threads
4. Stop waiting for user response after a certain amount of time

2020-12-24 04:09 UTC, charlotte-zhuang commented on src/nonPrefixCommands/threads/threadMessage.js
> +    switch (reaction.emoji.name) {
Wrapping around would be nice (like set the page to 0 by going right from the last page)

2020-12-24 04:09 UTC, charlotte-zhuang commented on src/nonPrefixCommands/threads/threadMessage.js
> +  const messageCollector = message.channel.createMessageCollector(filter);
Add a time limit to the collectors (end collection and delete displayed message after like a few minutes)

2020-12-24 04:09 UTC, charlotte-zhuang commented on src/nonPrefixCommands/threads/threadMessage.js
> +  let page = {
If all the threads fit on one page, there's no need for pagination.

2020-12-24 18:21 UTC, charlotte-zhuang requested changes
See comments:

1. There are a few ways to make your command error
2. The user's original message probably shouldn't be deleted, unless it has no arguments (for viewing a thread)
3. Some doc comments are incorrect
4. A few other items to consider

Also, the `|<thread ID>|` no arguments command should display a full thread (all its messages). It's how users actually use a thread. I don't think this needs to be added right now, but that's the goal.

We also need to change the `Command.js` class to remove the `params` member and add a `disabled` member (like what Sam did for the help command). Disabled non-prefix commands should be ignored by `NonPrefixRegexCreator.js` and should not be added to the command map in `NonPrefixHandler.js`. This might be done in a separate branch.

2020-12-24 18:21 UTC, charlotte-zhuang commented on src/nonPrefixCommands/threads/threadMessage.js
> +    threadListEmbed[0].addField('Choose one!', 'Example: "1"');
I think this field and the blank field look really weird. What do you think of changing it to `threadListEmbed[0].setDescription('Choose one! Example: "1"')`? Same thing on line 287.

2020-12-24 18:21 UTC, charlotte-zhuang commented on src/nonPrefixCommands/threads/threadMessage.js
>      await message.delete();
I think this might be causing other errors too, when you later reference a message that was deleted. I'm not sure though.

2020-12-24 18:21 UTC, charlotte-zhuang commented on src/nonPrefixCommands/threads/threadMessage.js
> + * @param {araay} queryThread the response from FIND_THREAD(data).
`queryThread` is an `Object`, not an `Array`.

2020-12-24 18:22 UTC, charlotte-zhuang commented on src/nonPrefixCommands/threads/threadMessage.js
> +  return await
bump

2020-12-27 09:14 UTC, jerrylee17 commented
[Here](https://github.com/SCE-Development/SCE-discord-bot/compare/patrick) there are 2 files that have been changed

However, this PR says that there are 8 files changed.
![image](https://user-images.githubusercontent.com/26675745/103167552-c5b2ae00-47e0-11eb-90b0-4b73128423c3.png)

github hello?????????????????????????????????????

2020-12-27 12:24 UTC, jerrylee17 requested changes
1. Enable `commands/threads/thread` and `commands/threads/threadmanager` in this pr since the thread functionality will be done. 
2. The functionality for showing the full thread does not work for me. It shows 1 thread only. See this image:
![image](https://user-images.githubusercontent.com/26675745/103167743-9e5ce080-47e2-11eb-8771-f78feef765c7.png)
3. When I enter an invalid thread ID, I get this error. Probably display an embed saying "there are no threads that start with blahblahblah"
![image](https://user-images.githubusercontent.com/26675745/103167785-06abc200-47e3-11eb-997f-404d8dae3484.png)
4. I think the current method of creating a new thread is janky. Perhaps we can make the rest of the message the topic (Basically same thing as doing `s!thread`. Also do a check on the topic length and if it's over a certain amount, give it a warning.

2020-12-27 12:24 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +  queryThread.responseData
I'm a lazy programmer and you used this functionality more than once so maybe make it a function

2020-12-27 12:24 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +async function pagination(data, message, queryThread, messageMode){
More comments in the code might be better. I spent like 30 mins trying to understand everything going on (my brain also tired so that might be why).

2020-12-27 12:24 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +  await currentMsg.react('⏹️');
I don't think the stop functionality is really necessary. It is usually helpful to keep the embed up for a while.

2020-12-27 12:24 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +    currentMsg.delete();
Don't delete - might be helpful to have later

2020-12-27 12:24 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +  let filter = (m) => {
Make this so that if the user has to immediately choose right after the modal. End the messagecollector after collecting 1 message (from the author), and if the message doesn't match, reply with something like "Sorry that's not a valid index blah blah blah".

Also, does the messageCollector collect messages from people that are not the author?

2020-12-29 07:03 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +        .send('Error')
^^ Makes it more verbose so people know where the error is

2020-12-29 07:03 UTC, jerrylee17 commented on src/commands/threads/thread.js
bump

2020-12-29 07:04 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +async function createNewThread(data, message){
Probably should be done in a new PR

2020-12-29 07:06 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +      .send('Not created')
bump

2020-12-29 07:06 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +      .send('Not created')
bump

2020-12-29 07:12 UTC, jerrylee17 requested changes
1. If I type an invalid ID, it deletes my message. Probably if theres nothing returned, display an embed telling them that there's nothing returned so the user isn't like "what happened to my message"
Also, I get this error:
![image](https://user-images.githubusercontent.com/26675745/103265147-c1fa6500-4961-11eb-9b7f-cd14acbcf2ad.png)
2. I think the current method of creating a new thread is janky. Perhaps we can make the rest of the message the topic (Basically same thing as doing s!thread. Also do a check on the topic length and if it's over a certain amount, give it a warning.
3. Enable commands/threads/thread and commands/threads/threadmanager in this pr since the thread functionality will be done.

2021-01-07 05:35 UTC, charlotte-zhuang requested changes
## Changes Made

I made a bunch of changes to the API functions: the arguments are different now and all functions require a guild ID now.
I also added the disabled option to non-prefix commands.

## Changes Reqested

1. Error if a user deletes a message in a thread. This is because you try to display a deleted message. When you encounter a message that has been deleted, use the `DELETE_THREADMESSAGE` function to delete the message from the thread, then skip the message.
2. Error if a user adds a message longer than 256 characters. This is because you display messages as headers, which are limited at 256 characters. Messages should be displayed in the body so that they're not limited (I think).
3. Multi-line messages should be supported. This isn't exactly critical, but definitely preferred.
4. The `nonPrefixCommands` folder should only contain commands; don't put extra functions inside that `nonPrefixFunctions` folder. Right now the functions in that folder are specific to your commands anyway, so move them into the same file. Later on we'll want to add some of those functions to `util` and some of them in a new `components` folder.
5. Your doc comments are much better, but still not formatted correctly. If you aren't sure how to write a doc comment, it's better to change it into a normal comment or keep it simple.

2021-01-07 05:35 UTC, charlotte-zhuang commented on src/nonPrefixCommands/nonPrefixFunctions/pagination.js
> +async function pagination(templateEmbed, message,
If there's only one page, don't react with arrows and wait for reactions (just display the content).

2021-01-07 05:35 UTC, charlotte-zhuang commented on src/nonPrefixCommands/nonPrefixFunctions/pagination.js
> +async function createThreadEmbed(threads,
Error if a header is over 256 characters.

2021-01-07 05:35 UTC, charlotte-zhuang commented on src/nonPrefixCommands/threads/threadMessage.js
> +    const data = {
I think it's much better practice to not make a generic dump of all the variables you need (most functions don't need most of these variables, so don't pass it to them).

2021-01-07 05:43 UTC, lupatrick13 commented on src/nonPrefixCommands/nonPrefixFunctions/pagination.js
> +async function pagination(templateEmbed, message,
I think i've already done that. It checks the max pages in the pagination function

2021-01-07 05:44 UTC, charlotte-zhuang commented on src/nonPrefixCommands/nonPrefixFunctions/pagination.js
> +async function pagination(templateEmbed, message,
The code doesn't error, but the reactions still show up at the bottom if that makes sense.

2021-01-12 06:14 UTC, charlotte-zhuang commented
## Changes Made

1. So I forgot to push my last commit, this time I actually fixed the API functions.
2. Moved functions into one file (they can be moved into a util or components folder later)
3. Multiple matched threads now display the last message, not the first. Messages that have been deleted on discord are also deleted on the database.
4. Showing a thread now includes the first message. The first message isn't special (the original message creating the thread could have been deleted)
5. Added catching to message deletes.
6. Other bug fixes

Things got toasty while I made all these changes, so another review would be good.

2021-01-12 06:17 UTC, charlotte-zhuang reviewed
Made changes.

2021-01-12 15:32 UTC, jerrylee17 requested changes
Review #1: Everything but the 619 line file has been commented.

`src/nonPrefixCommands/threads/threadMessage.js` is pretty tough to review. Probably move the functions to a separate file and import them from here.

2021-01-12 15:32 UTC, jerrylee17 commented on src/APIFunctions/thread.js
> +    query($guildID: String!) {
Enable this query to take in guildID, channelID optionally.
```
query($guildID: String, $channelID: String) {
  threadMany(filter: { guildID: $guildID, channelID: $channelID }) {
         ...
```

2021-01-12 15:32 UTC, jerrylee17 commented on src/APIFunctions/thread.js
> +  args = { ...args };
Aren't you just assigning args to itself here? Is there a purpose for this statement?

2021-01-12 15:32 UTC, jerrylee17 commented on src/commands/threads/thread.js
> +      const response = await THREAD_QUERY({ guildID: message.guild.id });
Query by both guildID and channelID

2021-01-12 15:32 UTC, jerrylee17 commented on src/commands/threads/thread.js
> +        if (thread.channelID !== message.channel.id) {
This can be omitted if you query by both guildID and channelID

2021-01-12 15:32 UTC, jerrylee17 commented on src/APIFunctions/thread.js
> +const THREAD_ID_QUERY = async args => {
`THREAD_ID_QUERY` and `THREAD_QUERY` can be combined into a single query. It may require some fixing up such as checking for `args.threadID` parameter but this would overall make the queries simpler from the client side. This would be easier if implemented in this pull request since the longer we wait the harder it will be to refactor.

2021-01-12 15:32 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +const Discord = require('discord.js');
This file is 619 lines... We should split it into multiple files to make it more readable.
All those functions after line 119 --> Put it into a new file and import them in.

2021-01-12 15:32 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> + * @param {import('../threads/threadMessage').Data} data
Interesting docstring... the import is not required since it is in the same file.

2021-01-12 16:10 UTC, jerrylee17 requested changes
Review 2: Bug I found

This functionality is actually really developed and I think we are almost done!

1. I unintentionally added a message to 2 threads with 1 message. How did I do this?
```
me: |8994| add this message
bot: pops up a modal of all threads that start with 8994
me: |89944| add this other message
bot: pops up another modal of all threads that start with 89944
me: 2
bot: adds "add this message" to the 2nd result in the first modal
bot: adds "add this other message" to the 2nd result in the second modal
```
Solution: 
Only collect the message sent by the user immediately following the modal. In the example, the bot would make the first modal inactive as soon as the user enters an invalid number.

2. How to get an error creating thread
```
Channel 1: I have a thread with the ID 8994283609061
In Channel 2:
me: |8994283609061| jerry makes a thread with an existing ID
bot: Error creating
```
Suggestion: 
Instead of giving a vague " Error Creating", go with something like "ID has been taken. Choose a different ID or let the bot autogenerate it with `s!thread` blah blah blah".

2021-01-12 19:05 UTC, charlotte-zhuang commented on src/APIFunctions/thread.js
> +  args = { ...args };
This is necessary to avoid changing the input object.

2021-01-12 19:05 UTC, charlotte-zhuang commented on src/APIFunctions/thread.js
> +    query($guildID: String!) {
I thought guildID would be mandatory since you shouldn't query outside your own guild?

2021-01-12 19:08 UTC, charlotte-zhuang commented on src/nonPrefixCommands/threads/threadMessage.js
> +const Discord = require('discord.js');
My issue is that the functions are a bit convoluted. I guess there could be a `nonPrefixCommands/threads/threadMessageUtil/` directory for the extra functions?

2021-01-12 20:57 UTC, charlotte-zhuang commented on src/nonPrefixCommands/threads/threadMessage.js
> +const Discord = require('discord.js');
Putting any non command directories in `nonPrefixCommands` would require minor changes to the handlers and `nonPrefixRegexCreator.js`. Patrick used to put the util in `nonPrefixCommands/threadFunctions` which works since normally only commands are stored in second level directories.

2021-01-12 20:59 UTC, charlotte-zhuang commented
## Changes for dcd885f

1. Thread API changes
2. Asking user to choose a thread now only waits for one message from the user
3. Fixed bug where thread messages would be deleted on other errors
4. Fixed bug where `threadMessage.js` would error when displaying a messages that did start with `|<id>|` or `s!thread`

2021-01-15 03:50 UTC, charlotte-zhuang commented on src/nonPrefixCommands/threads/threadMessage.js
> +const Discord = require('discord.js');
Moved functions to `threadMessageUtil.js`

2021-01-15 03:51 UTC, charlotte-zhuang commented
## Changes for 659d6fd

1. Moved utility functions to `threadMessageUtil.js`
2. Cleaned up comments
3. Minor refactor to functions for readability

2021-01-15 16:14 UTC, jerrylee17 approved these changes
Code looks awesome! It's readable and scalable :+1: 

Some braindump...
1. The error is because `8994283609061` already exists in another channel. Would be better to give a more verbose error message.

![image](https://user-images.githubusercontent.com/26675745/104750428-f19ec080-5708-11eb-855a-c6b61b6ecf23.png)

2. A thread with 50+ messages is going to be nasty to scroll through

![image](https://user-images.githubusercontent.com/26675745/104750616-3296d500-5709-11eb-8b5a-24bb5514de2a.png)

3. I think we will be using pagination a lot in the future. We should probably make it a component initialized with a class (in another pr). 

4. As clear as the instructions for using threads is, we should probably write up some documentation on it with a reference.

This is the biggest PR in SCE-development right now no cap. Great job @lupatrick13 and @charlotte-zhuang!!!

2021-01-15 16:20 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessageUtil.js
> +      pagination(templateEmbed, message, threadQuery2.responseData, true);
Remove the `true`

2021-01-16 05:35 UTC, qsaml commented
things I noticed :

- right now, you're allowed to type a random threadID that may or may not exist and it will ask to create the ID, not sure if that is an intentional feature. maybe it's better to just have threads created by threadmanager
- you can't just randomly type 4 numbers of a threadID after it's created and it will add on to a thread (you have to use the same 4 numbers). example : say a threadID is 59596943, typing `|5959|` will start a thread, but you can't add on to it by typing `|9596|`, it starts a new thread
- basically, add to the new thread message embed to type the same 4 numbers that the thread was created with or the full ID
- I feel like the first message of the thread shouldn't be the message creating the thread, as here
![image](https://user-images.githubusercontent.com/66745211/104798157-1468bd80-5779-11eb-8105-7658e2704489.png)

regarding jerry's comments I agree with them, but holy moly this might be the best thing I've seen to now

2021-01-16 06:54 UTC, seemavora reviewed
I gotta say this is an amazing project, looks pretty good so far!!
![image](https://user-images.githubusercontent.com/29296452/104799442-04a2a680-5784-11eb-8de2-1cf86a36831e.png)
A few suggestions I have:
1. Maybe at the beginning of your PR include what changes you made and what commands/things you want ur PR reviewer to test, since that was slightly unclear. 
2.  I think this was mentioned before but changing the thread id creates a new thread
3. maybe might also be cool to create names for the threads instead of thread ids its too painful to type in a long number

2021-01-16 06:56 UTC, seemavora reviewed
Also i gotta say ur code is CLEANNNN  compared to a lot of PRS i have seen go you!

2021-01-17 22:42 UTC, charlotte-zhuang commented
## Changes in 5ab3d4d and 0bea8cd

1. Fixed bug when paginating a thread after selecting from multiple options
2. Added thread ID decoration for readability
3. Moved thread ID functions to util

## Not changed

`threadmessages.js` still creates a new thread when the specified ID is not found. Is there a good reason to keep this?

2021-01-17 22:43 UTC, charlotte-zhuang approved these changes

2021-01-20 16:59 UTC, jerrylee17 requested changes
1. `npm run lint`
2. Using \` will also add in the extra line breaks and spaces. Use `'` instead
![image](https://user-images.githubusercontent.com/26675745/105207837-de229980-5afc-11eb-9645-37a130f7d9fe.png)

2021-01-20 16:59 UTC, jerrylee17 commented on src/commands/threads/thread.js
> +  example: `${prefix}thread <all | active | none | topic>`,
I like this! We should do this for more commands in a future pr

2021-01-20 16:59 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +    if (threadID.length < 4) {
Won't ever happen because of the regex.................................


just kidding nice catch

![image](https://user-images.githubusercontent.com/26675745/105208464-92242480-5afd-11eb-82fa-6d49ac1e7866.png)

2021-01-21 04:49 UTC, jerrylee17 commented on src/util/threadMessage.js
> +        `Error creating. Possibly an existing thread uses ID
I used
```
'Error creating. Possibly an existing thread uses ID ' +
`${decorateId(threadID)}.`
```

2021-01-24 07:00 UTC, charlotte-zhuang commented
## Changes in 31ac029

1. I fixed the string literal formatting issues, and also change that error message since I wasn't sure if it was accurate.
2. Fixed bug where prefixed commands can create topics that are too long.
3. Simplified API function code (sorry, I hate my code)

2021-01-28 01:08 UTC, closed without merging