Thread Prefix Commands
SCE-Development/SCE-discord-bot pull request #114
Opened 2020-12-22 06:20 UTC by charlotte-zhuang

## Changes

1. Created thread and thread manager commands.
2. Added thread query by thread id using regex to API Functions.

## Features

1. View active or all threads (general thread)
2. Create new threads (general thread and thread manager)
3. Delete thread (thread manager)

2020-12-22 06:41 UTC, jerrylee17 requested changes
Testing this PR in a bit

2020-12-22 06:41 UTC, jerrylee17 commented on src/commands/threads/thread.js
> +  example: 's!thread <param (optional)>',
For example naming convention, we're using [this](https://github.com/SCE-Development/SCE-discord-bot/wiki/Example-naming-convention)
Use bracket: `s!thread <[active | all | none] | topic>`

This means: 
There is 1 required parameter, and it can optionally be "active", "all", or "none". If it is not any of these, it becomes the topic of the thread.

2020-12-22 06:41 UTC, jerrylee17 commented on src/commands/threads/thread.js
> +  params:
Params has been removed from the structure of a command so this is not needed

2020-12-22 06:41 UTC, jerrylee17 commented on src/commands/threads/threadManager.js
> +  params: '`create`, `remove`',
Params has been removed

2020-12-22 06:41 UTC, jerrylee17 commented on src/commands/threads/threadManager.js
>    example: 's!tm',
`s!tm [create | remove]`

2020-12-22 10:31 UTC, jerrylee17 commented
For now, make these commands (`s!thread`, `s!tm`) disabled by adding (`disabled: true`). We will enable them when the final product is ready to be pushed out.

2020-12-22 10:36 UTC, jerrylee17 commented
![image](https://user-images.githubusercontent.com/26675745/102879183-4139e700-43fe-11eb-95fe-2b5fa5a79fda.png)
For stuff like `s!tm create <topic>`, wrap it in \` (Just a personal preference)

For `s!tm create <topic>`, if <topic> is optional, just make it `s!tm create [topic]`

2020-12-22 10:52 UTC, jerrylee17 commented
This is my fault on the outdated query/mutation, but I recently found this out.

For the mutation on CREATE_THREAD, do this
```
mutation(
  $threadID: String!
  $creatorID: String!
  $guildID: String!
  $topic: String
  $messageID: String!
) {
  threadCreate(
    threadID: $threadID
    creatorID: $creatorID
    guildID: $guildID
    topic: $topic
    messageID: $messageID
  ) {
    threadID
    creatorID
    guildID
    topic
    threadMessages {
      messageID
    }
  }
}
```
Then, when you call the request, you can just do this: 
```
await request(`${DISCORD_API_URL}/graphql`, makeThreadMessage, {
    threadID, creatorID, guildID, topic, messageID
  })
```
Basically, rather than hardcoding the variables in, you make the code more flexible and you pass in a parameter.
Old code: 
```
mutation {
    threadCreate(
      threadID:"${threadID}",
      creatorID:"${creatorID}",
      guildID:"${guildID}",
      topic:"${topic}",
      messageID:"${messageID}"
    ) {
      threadID
      creatorID
      guildID
      topic
      threadMessages {
        messageID
      }
    }
  }
```
```
await request(`${DISCORD_API_URL}/graphql`, makeThreadMessage)
```
Could you do a quick refactor of these queries/mutations with your PR?

2020-12-22 11:00 UTC, jerrylee17 commented
What's the difference between an active thread and an inactive thread? Might want to put the distinction somewhere

2020-12-22 11:20 UTC, jerrylee17 reviewed
threadManager comments

2020-12-22 11:20 UTC, jerrylee17 commented on src/commands/threads/threadManager.js
> +    const confirmAction = async (create, info) => {
I like the way you designed this confirmAction embed. Perhaps we can move it to a separate file for others to use it. 

There would probably need to be a few tweeks to it (callback, info, configurations) and a few modifications but I think it would overall make the code more scalable

2020-12-22 11:20 UTC, jerrylee17 commented on src/commands/threads/threadManager.js
> +          confirmEmbed.addField('Topic', info[2]);
It should be `info[1]`

2020-12-23 08:01 UTC, charlotte-zhuang commented on src/commands/threads/threadManager.js
> +          confirmEmbed.addField('Topic', info[2]);
Nice catch

2020-12-23 08:02 UTC, charlotte-zhuang commented on src/commands/threads/threadManager.js
> +    const confirmAction = async (create, info) => {
TBD

2020-12-23 08:03 UTC, charlotte-zhuang commented
> A vulnerability with threadManager is that you can delete threads from other guilds as long as you have the ID to it. It can be exploited like this:
> 
> 1. Create a dummy server, invite SCE bot. Since you are an "admin" of that server, you can manage threads.
> 2. In SCE server, type `s!thread all` to get a list of every thread
> 3. In the dummy server, use `s!tm remove <threadID>` to remove threads
> 
> To resolve this, make sure that the message thread being removed is in the same guild as where the message is being sent (ex: message.guild === thread.guildID)

I changed thread manager to filter threads based on guild id. I'm not sure how I can test it though.

2020-12-23 08:11 UTC, charlotte-zhuang commented on api/resolvers/thread.js
> +  threadMessageDelete: {
This resolver only needs two mutations (delete `threadMessage`, pull element from `thread`), but I couldn't get it to work. Since `thread` stores documents in the `threadMessages` array, I can only remove by `ObjectID` (which I get with a query using `messageID`). I also tried deleting `threadMessage` first, which turns its entry in `threadMessages` into `null`; however, I couldn't pull `null` from `threadMessages`.

2020-12-23 08:19 UTC, charlotte-zhuang commented on src/commands/threads/threadManager.js
> +        const threads = query.responseData.filter(
Untested security to prevent deleting threads from other guilds.

2020-12-23 08:26 UTC, charlotte-zhuang commented
## Changes for 1534bed

1. Fixed descriptions and disabled commands
2. Refactored API functions
3. Added resolver and function to delete thread message
4. When using `s!thread <all | active>`, deleted messages will be deleted from Mongo
5. Added `channelID` to thread schema (allows for differentiating between a deleted message and one in another channel)
6. Added guild ID filter to thread manager remove command (untested)

2020-12-24 01:03 UTC, jerrylee17 approved these changes
Nice job!

2020-12-24 01:03 UTC, jerrylee17 commented on src/commands/threads/threadManager.js
> +        const threads = query.responseData.filter(
![image](https://user-images.githubusercontent.com/26675745/103047520-a4cc2d80-4540-11eb-9c11-65ecf217be5d.png)
![image](https://user-images.githubusercontent.com/26675745/103047508-9b42c580-4540-11eb-9141-b91ea3e9cfa8.png)

I tested it and it worked :)

2020-12-24 03:34 UTC, charlotte-zhuang commented
## Changes for 8f90280

1. Added catch statements for deleting messages (if a user deletes the message before the bot does)
2. Added documentation comments to thread API functions

2020-12-24 05:18 UTC, jerrylee17 approved these changes
Nice documentation!

2020-12-24 19:17 UTC, merged