Chris-Evan-Collab2.0
SCE-Development/SCE-discord-bot pull request #123
Opened 2021-03-09 01:28 UTC by Christopher-Tom

2021-03-09 01:33 UTC, hsorathia approved these changes

2021-03-09 01:34 UTC, seemavora approved these changes

2021-03-09 01:38 UTC, jerrylee17 approved these changes
A few questions:

1. Does this automatically run `npm install` (not that it really matters that much)?
2. Are there any limitations to how many times you can run CI? For ex: Travis-ci gives us a set amount of points so you cannot keep running it

2021-03-09 01:38 UTC, jerrylee17 commented on .github/workflows/main.yml
> +on:
Should probably also do `on: push` so its run every time you push

2021-03-09 01:57 UTC, evanugarte commented on .github/workflows/main.yml
> +on:
resolving this as we decided to just do prs in discord
![image](https://user-images.githubusercontent.com/36345325/110406887-cd3fd000-8037-11eb-8ed1-8791cfc792dd.png)

2021-03-09 01:58 UTC, evanugarte commented
@jerrylee17 
1. yes
2. yes, but i doubt we will exceed it

2021-03-09 02:24 UTC, charlotte-zhuang requested changes
I requested some changes.
btw, i was looking at [this](https://docs.github.com/en/actions/guides/building-and-testing-nodejs, [this](https://github.com/actions/setup-node/), and [this](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software) for reference on GitHub actions. I'm not really sure if what I understand is accurate.

2021-03-09 02:24 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +    branches: [ master ]
I think we could change this to run on all PRs, not just for master.

2021-03-09 02:24 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +          node-version: ${{ matrix.node-version }}
I don't think `matrix` is defined? If we don't specify `with`, will it use get the right version of node?

2021-03-09 02:38 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +          node-version: ${{ matrix.node-version }}
Actually, maybe it's best to specify `matrix.node-version` with `14.x` to match `package.json`.

2021-03-09 02:45 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +    runs-on: ubuntu-latest
`runs-on: ubuntu-18.04` would match our production env.

2021-03-10 04:06 UTC, ThaiQ approved these changes

2021-03-11 00:59 UTC, evanugarte commented on .github/workflows/main.yml
> +          node-version: ${{ matrix.node-version }}
```suggestion
          node-version: 14.x
```

2021-03-11 01:00 UTC, evanugarte commented on .github/workflows/main.yml
> +      - name: Use Node.js ${{ matrix.node-version }}
```suggestion
      - name: Use Node.js 14.x
```

2021-03-11 01:02 UTC, evanugarte commented on .github/workflows/main.yml
> +    branches: [ master ]
this means run the test when we open a pr for master, this pr is an example

2021-03-11 02:04 UTC, charlotte-zhuang requested changes
Requested changes to OS version primarily. Also wondering about `pull_request:`

2021-03-11 02:04 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +    runs-on: ${{ matrix.os }}
Any reason why we're using a matrix?

I think we should change it to `runs-on: ubuntu-18.04`

2021-03-11 02:04 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +    branches: [ master ]
bump

2021-03-11 02:05 UTC, charlotte-zhuang commented on .github/workflows/main.yml
> +    runs-on: ubuntu-latest
new comment on the same code

2021-03-13 22:23 UTC, charlotte-zhuang approved these changes

2021-03-13 22:25 UTC, merged