Points Function
SCE-Development/SCE-discord-bot pull request #132
Opened 2021-04-09 01:00 UTC by qsaml

Points functionality added. Checks a user's points by `s!pts` and displays an embed depending on whether a user is mentioned or not. Checks every message and if it is 3 minutes from user's last message, add a random number of points.

2021-04-11 06:09 UTC, evanugarte commented on api/models/points.js
> +let p = Math.floor(Math.random() * (50 - 25) + 25);
use `const` since we initialize this variable and dont change it
```suggestion
const p = Math.floor(Math.random() * (50 - 25) + 25);
```

consider renaming `p` to something more descriptive, e.g. `defaultPoints` and add a comment for why `p` is calculated this way

2021-04-11 06:09 UTC, evanugarte commented on api/resolvers/points.js
> +// const { Aggregate } = require('mongoose');
remove if we arent using this anymore
```suggestion
```

2021-04-11 06:11 UTC, evanugarte commented on src/util/Points.js
> +  let p = Math.floor(Math.random() * (50 - 25) + 25);
it seems like we are using `p` in more than one place, what if we define a function that returns `Math.floor(Math.random() * (50 - 25) + 25)`?

2021-04-11 06:13 UTC, evanugarte commented on src/util/Points.js
> +  let c = 180000;
if this is a standard for points, consider defining this value in `../APIFunctions/points.js` like `POINTS_COOLDOWN_TIME`

2021-04-11 06:14 UTC, evanugarte commented on src/util/Points.js
> +    points.lastTalked = message.createdAt;
```suggestion
    points.lastTalked = createdAt;
```

2021-04-11 06:15 UTC, evanugarte commented on src/util/Points.js
> +  let createdAt = message.createdAt;
the below line works the same
```suggestion
  const { lastTalked, createdAt } = points;
```

2021-04-11 06:34 UTC, qsaml commented on api/models/points.js
> +let p = Math.floor(Math.random() * (50 - 25) + 25);
my thing about using `let` vs `const` was that the value of `p` changes each time it instantiates, but yeah. looking at this

2021-04-12 18:55 UTC, evanugarte commented on api/models/points.js
> +let p = Math.floor(Math.random() * (50 - 25) + 25);
if you want it to consistently change consider making a helper function

2021-06-30 01:33 UTC, charlotte-zhuang requested changes
See comments. Also, not planning to merge these changes for a while to wait for other utils to be merged.

2021-06-30 01:33 UTC, charlotte-zhuang commented on package.json
> +    "fetch": "^1.1.0",
Is this a mistake?

2021-06-30 01:33 UTC, charlotte-zhuang commented on src/APIFunctions/points.js
> +// Function to query the user's points based on server ID and Discord ID
```suggestion
/**
 * Query points for a user or users.
 *
 * @param args.guildID { String }
 * @param args.userID { String? } Optional. Query one user if specified, otherwise query entire guild
 * @returns { ApiResponse } Response with an array of matched user points.
 */
```

Please make JSDoc comments for the exported functions.

2021-06-30 01:33 UTC, charlotte-zhuang commented on src/commands/member_services/points.js
> +  permissions: 'member',
Add an example. [See wiki](https://github.com/SCE-Development/SCE-discord-bot/wiki/Example-naming-convention).

2021-06-30 01:33 UTC, charlotte-zhuang commented on src/commands/member_services/points.js
> +      if (point === undefined) {
```suggestion
      if (!point) {
```
This is more clear.

2021-06-30 01:33 UTC, charlotte-zhuang commented on src/commands/member_services/points.js
> +    if (point === undefined) {
see

2021-06-30 01:33 UTC, charlotte-zhuang commented on src/commands/member_services/points.js
> +    return;
```suggestion
```
Pointless return statement

2021-06-30 01:33 UTC, charlotte-zhuang commented on src/commands/member_services/top.js
> +function checkPoints(a, b) {
```suggestion
function comparePoints(a, b) {
```

2021-06-30 01:33 UTC, charlotte-zhuang commented on src/commands/member_services/top.js
> +        topEmbedCapped.addField('Number ' + (i + 1), `<@${data[i].userID}> `
```suggestion
        topEmbedCapped.addField(
          'Number ${i + 1}`,
          `${fetchThierNicknameHere(data[i].userID)} {data[i].totalPoints}`
        );
```

2021-06-30 01:33 UTC, charlotte-zhuang commented on src/util/CooldownManager.js
> +   * @member {Discord.Collection} pointsCooldown Maps user ID's to a
Why did you add this comment?

2021-06-30 01:33 UTC, charlotte-zhuang commented on src/util/Points.js
> +  return Math.floor(Math.random() * (50 - 25 + 1) + 25);
```suggestion
  return Math.floor(Math.random() * 26 + 25);
```

2021-06-30 01:33 UTC, charlotte-zhuang commented on src/util/Points.js
> +// Random point value to add, between 25 and 50 inclusive
JSDoc pls

2021-06-30 01:33 UTC, charlotte-zhuang commented on src/util/Points.js
> +// Gets the week of the month for point resets
JSDoc pls

2023-07-12 06:40 UTC, evanugarte commented
https://www.youtube.com/watch?v=6dPMOotLMiQ

2023-07-12 06:40 UTC, closed without merging