Ladykillah
SCE-Development/SCE-discord-bot pull request #145
Opened 2022-06-29 19:35 UTC by phuvu0107

2022-07-06 03:28 UTC, neelp03 requested changes
Some of the variables and functions need to be renamed so they can be understood just by reading the name. The closer we can get our code to reading like it was plain instructions, the better. You can use short forms but use the ones that can be understood by others ig. Also don't forget to make a new file for all this, you are currently editing the ping command

2022-07-06 03:28 UTC, neelp03 commented on src/APIFunctions/CheckDiscordID.js
> +    .get(MAINENDPOINTS_API_URL + '/User/checkUserIDTest', {params: {...IDTest}})
You can directly send the items of ID test without making another property to store it in the request

```js
axis.get(url, {...IDTest})
```

2022-07-06 03:28 UTC, neelp03 commented on src/commands/util/ping.js
> +    // const file = message.author.lastMessageID;
You are editing the Ping command. What you really should be doing is making a new file for the printing commands. So put ping.js back to how it was before and make a new file.

2022-07-06 03:28 UTC, neelp03 commented on src/commands/util/ping.js
> +
maybe add logic check where if the user attaches multiple documents but this can be done in the future

2022-07-06 03:28 UTC, neelp03 commented on src/commands/util/ping.js
> +        checkingInProcess.edit('Invalid API Key! Unable to print!');
Maybe make this a boolean check for simplicity
```js

    const checkingInProcess = await message.channel.send('Checking user ID...');
    const {exists}  = await CheckDiscordID.checkID(checkUser);

    if(exists){
      const response = await SendFileURL.allowPrinting(checkURL);
      
      if(response.error){
        checkingInProcess.edit('Invalid API Key! Unable to print!');
```

2022-07-08 22:28 UTC, evanugarte commented on src/APIFunctions/SendFileURL.js
> +module.exports = allowPrinting;
```suggestion
module.exports = { sendPrintRequest };
```

2022-07-08 22:28 UTC, evanugarte commented on src/APIFunctions/SendFileURL.js
> +async function allowPrinting(checkURl){
```suggestion
async function sendPrintRequest(checkURl){
```

2022-07-08 22:28 UTC, evanugarte commented on src/APIFunctions/SendFileURL.js
> +const ApiResponse = require('./ApiResponses');
```suggestion
const { ApiResponse } = require('./ApiResponses');
```

2022-07-08 22:28 UTC, evanugarte commented on src/APIFunctions/SendFileURL.js
> +  let status = new ApiResponse.ApiResponse();
```suggestion
  let status = new ApiResponse();
```

2022-07-08 22:28 UTC, evanugarte commented on src/APIFunctions/CheckDiscordID.js
> +const checkID = async (discordID) =>{
```suggestion
const checkIfDiscordAccountConnectedToUser = async (discordId) =>{
```

2022-07-08 22:28 UTC, evanugarte commented on src/APIFunctions/CheckDiscordID.js
> +const ApiResponse = require('./ApiResponses');
```suggestion
const { ApiResponse } = require('./ApiResponses');
```

2022-07-08 22:28 UTC, evanugarte commented on src/APIFunctions/CheckDiscordID.js
> +  let status = new ApiResponse.ApiResponse();
```suggestion
  let status = new ApiResponse();
```

2022-07-08 22:28 UTC, evanugarte commented on src/APIFunctions/CheckDiscordID.js
> +module.exports = checkID;
```suggestion
module.exports = { checkIfDiscordAccountConnectedToUser };
```

2022-07-08 22:28 UTC, evanugarte commented on src/commands/member_services/print.js
> +const CheckDiscordID = require('../../APIFunctions/CheckDiscordID');
```suggestion
const { checkIfDiscordAccountConnectedToUser } = require('../../APIFunctions/CheckDiscordID');
```

2022-07-08 22:28 UTC, evanugarte commented on src/commands/member_services/print.js
> +    const {exist, mess}  = await CheckDiscordID(checkUser);
```suggestion
    const {exist, mess}  = await checkIfDiscordAccountConnectedToUser(checkUser);
```

2022-07-08 23:14 UTC, neelp03 commented on src/APIFunctions/CheckDiscordID.js
> +module.exports = checkID;
maybe a shorter name?? like validateDiscordAuth or checkDiscordConnection

2022-07-23 04:08 UTC, neelp03 requested changes

2022-07-23 06:46 UTC, neelp03 requested changes
Everything looks good, just need some finishing touches and then we are good to go with this pr

2022-07-23 06:46 UTC, neelp03 commented on src/APIFunctions/Print.js
> + * @param {Number} printedPages
Change documentation variable since you changed the name of the variable

2022-07-23 06:46 UTC, neelp03 commented on src/commands/util/getPdfNumOfPages.js
> + * @param {string} pdfPath - path to the pdf file
Same here, update documentation

2022-07-26 17:38 UTC, neelp03 requested changes

2022-07-26 17:38 UTC, neelp03 commented on src/APIFunctions/Print.js
> +        const result = {
```suggestion
  return new Promise(( resolve ) => {
    axios.post(
        `${MAINENDPOINTS_API_URL}/getUserFromDiscordId`,
        {discordID, apiKey: CORE_V4_API_KEY}
    )
      .then((res) => {
        const {pagesPrinted} = res.data;
        const result = {
```

2022-07-26 17:38 UTC, neelp03 commented on src/commands/member_services/print.js
> +    })
```suggestion
    const filter = collected => collected.author.id === message.author.id;
    await message.channel.awaitMessages(filter, {max: 1, time: 15000})
```

2022-07-29 16:39 UTC, neelp03 approved these changes

2022-07-29 20:47 UTC, ShaivPandya approved these changes

2022-07-29 20:49 UTC, neelp03 requested changes

2022-07-29 20:49 UTC, neelp03 commented on src/commands/util/getPdfNumOfPages.js
> +module.exports = {getPdfNumOfPages};
```suggestion
  const pageCount = await pdfDoc.getPageCount();
  return pageCount;
}
module.exports = {getPdfNumOfPages};

```

2022-07-29 20:54 UTC, neelp03 requested changes

2022-07-29 20:54 UTC, neelp03 commented on src/APIFunctions/Print.js
> +        res.status === 200 && resolve(result);
I don't think you need to check if status is 200, if its not then it would throw error which is caught in the catch block which will just resolve false.

2022-07-29 20:54 UTC, neelp03 commented on src/APIFunctions/Print.js
> +let PERIPHERAL_API_URL = 'http://localhost:8081/peripheralapi';
??

2022-08-04 01:57 UTC, evanugarte approved these changes

2022-08-04 01:57 UTC, evanugarte commented on src/APIFunctions/Print.js
> + * Core-V4/main_endpoints/User.js to check if user's Discord ID is in database.
```suggestion
 * @summary Check if a given Discord ID exists in Core-v4's database.
```

2022-08-04 01:57 UTC, evanugarte commented on src/APIFunctions/Print.js
> +          pagesPrinted: pagesPrinted
```suggestion
          isValid: true, 
          pagesPrinted,
```

2022-08-04 01:57 UTC, evanugarte commented on src/commands/member_services/print.js
> +  execute: async (message, args) => {
do we need this line?
```suggestion
  execute: async (message) => {
```

2022-08-04 01:57 UTC, evanugarte commented on src/commands/member_services/print.js
> +      });
your combining callbacks and await here, i would instead just do
```suggestion
    try {
      const attachments = await message.channel.awaitMessages(filter, {max: 1, time: 15000})
      url = collected.first().attachments.first().url;
    } catch() {
      return reply.edit('Your time is up! Type "s!print"' +
      'command again to restart printing process!');
    }
```

2022-08-04 01:57 UTC, evanugarte commented on src/commands/member_services/print.js
> +      'command again to restart printing process!');
can we be a little more descriptive of the errors? if these come up when people are trying to use them, they will send us screenshots like "hey printing didnt work the bot said this can you help me?"

lets make life easier for us with messages like

```markdown
## if editUserPagesPrinted didnt work:
It's not you, it's us. We are unable to update the number of pages you have printed at this time.
Please try printing from the website or try again later! Don't worry, we didn't subtract from your
weekly page count.

## if pushDiscordPDFToSqs didnt work:
We couldnt push your print job to the folder! Report this error to an officer for a free SCE snack!
```

2022-08-07 20:44 UTC, neelp03 approved these changes

2022-08-07 20:45 UTC, merged