Set up backend / refactor server.js
SCE-Development/SCE-discord-bot pull request #78
Opened 2020-09-30 00:32 UTC by jerrylee17

2020-10-11 23:04 UTC, hsorathia requested changes
For the comments on the db stuff look at this:
![image](https://user-images.githubusercontent.com/36381158/95692397-48609f80-0bda-11eb-89f7-536b11463c51.png)

Overall, I think we can use more specific types in our database so documents stored into our collection will have more predictable values for their attributes. So even if we have good coding standards and enforce the policies within the code like we make sure we store date objects inside the lastTalked attribute, we can just mess up in one place and accidentally store something else that won't be caught by mongoose. Alternatively, we can use mongoose-timestamps and use the plugin to have an updatedat type field for the model and everytime we update an entity/object mongoose will automatically change the date for us.

Another thing I was thinking about is that the poitns schema seems to be doing a lot (it stores user information and their points). Then it might be better to change the name of this schema to User. Or, we could separate this into two schemas (user and points) and in points we have a reference to the user and vice-versa to establish a relationship between the two. With the latter method, if we decide to add more things like if we have an sce item tracker on the bot (that tracks if the user is currently borrowing an sce item like a logicboard) we can setup a new schema and then reference the user thing to it.

2020-10-12 20:27 UTC, jerrylee17 commented on server.js
> +  mongoose.set('useCreateIndex', true);
i dont know how to solve this

2020-10-12 20:36 UTC, jerrylee17 commented on server.js
> +    console.log('Connected to Mongo');
My dumbass used await on the connect lmao

2020-10-12 22:48 UTC, hsorathia commented on api/models/points.js
> +    // _id: mongoose.Schema.Types.ObjectId,
dont need this comment anymore tbh

2020-10-14 23:05 UTC, hsorathia approved these changes

2020-10-14 23:11 UTC, merged