Mute Command
SCE-Development/SCE-discord-bot pull request #87
Opened 2020-10-14 18:28 UTC by qsaml

Resolves #30

2020-10-14 22:10 UTC, jerrylee17 requested changes
Really good first PR. See comments

2020-10-14 22:10 UTC, jerrylee17 commented on src/commands/admin/mute.js
> +    if (!message.guild.member.id) {
This is returning an error for me. 

I don't think this is necessary because when you search for the user, you are using `const user = message.guild.member()`, which returns a user from the guild itself.

2020-10-14 22:11 UTC, jerrylee17 commented on src/commands/admin/mute.js
> +        .catch(() => {
If this isn't doing anything, can we just remove it?

2020-10-14 22:20 UTC, qsaml commented on src/commands/admin/mute.js
> +    if (!message.guild.member.id) {
I want there to be a distinct case when the user doesn't exist in the server, though. when I tested with another account, the bot gave `You must give a user to mute` when it should give `That user doesn't exist!`

I'll try to see if using `if (!user.id)` works

2020-10-15 00:20 UTC, jerrylee17 requested changes

2020-10-15 00:20 UTC, jerrylee17 commented on src/commands/admin/mute.js
> +    if (!user.id) {
Repetitive. All user objects stored in the database have ID's.

2020-10-15 00:23 UTC, jerrylee17 commented on src/commands/admin/mute.js
> +    if (!user.id) {
> I want there to be a distinct case when the user doesn't exist in the server, though. when I tested with another account, the bot gave `You must give a user to mute` when it should give `That user doesn't exist!`
> 
> I'll try to see if using `if (!user.id)` works

This won't work because `user` is pulled from all members in the guild already. So if you have a `user`, you will have a `user.id` and the guild that the user belongs to will be your current guild.

2020-10-15 00:43 UTC, jerrylee17 approved these changes
Nice job!

2020-10-15 01:03 UTC, IsitaB approved these changes
excellent work!

2020-10-15 01:04 UTC, merged