Architecture change for non-prefix commands
SCE-Development/SCE-discord-bot pull request #95
Opened 2020-10-21 03:27 UTC by charlotte-zhuang

1. Moved handlers to handlers folder
2. created MessageHandler to handle all messages
3. changed CommandHandler to only handle prefixed commands
3. created nonPrefixHanlder to handle non-prefix commands
4. created nonPrefixRegexCreator to match all non-prefix commands
5. created nonPrefixCommands directory and Commands class for non-prefix commands
6. created Thread and ThreadManager prefixed command boilerplates
7. created ThreadMessage non-prefixed command boilerplate

2020-10-22 00:15 UTC, jerrylee17 requested changes
![image](https://user-images.githubusercontent.com/26675745/96803354-f2051500-13c0-11eb-989e-0ab13e0ec45b.png)
Capitalize the thingy in messageHandler.

2020-10-22 00:15 UTC, jerrylee17 commented on src/handlers/MessageHandler.js
> +const { NonPrefixHandler } = require(handlersPath + '/nonPrefixHandler');
Capitalize `NonPrefixHandler`

2020-10-22 00:15 UTC, jerrylee17 commented on src/nonPrefixCommands/threads/threadMessage.js
> +  regex: new RegExp(/^\|(\d{1,18})\|\s+/),
Personal preference - I like having the space before/after the thread ID: `/^\|\s*(\d{1,18})\s*\|\s+/`

2020-10-22 01:35 UTC, jerrylee17 approved these changes
Nice job!

2020-10-26 02:43 UTC, jerrylee17 commented
@charlotte-zhuang you can probably merge this in

2020-10-26 02:58 UTC, charlotte-zhuang commented
Sorry, I didn't realize I needed to merge my PR.

2020-10-26 02:59 UTC, merged