Helpr
SCE-Development/SCE-discord-bot pull request #98
Opened 2020-10-30 21:27 UTC by RTX-Banana

Refactored Help Command

2020-11-03 07:08 UTC, jerrylee17 commented
Converted to draft - still work in progress

2020-11-13 23:41 UTC, charlotte-zhuang requested changes
Disabled commands are causing some issues in `src/commands/util/help.js`.
1. Line 90 crashes if `typeof infoText !== String`. I think this can be solved with a type check in the `capitalize` function on line 16.
2. Disabled commands are being displayed in `s!help`. On line 43, a check for `tmp[j].disabled` should do the trick.

2020-11-13 23:41 UTC, charlotte-zhuang commented on src/commands/util/help.js
>            infoText = capitalize(infoText);
Crashes if `field === 'disabled'`. The `disabled` field has a boolean value.
For example, try `s!help github`

2020-11-13 23:41 UTC, charlotte-zhuang commented on src/commands/util/help.js
>            infoText = capitalize(infoText);
Maybe it would be best to add a type check in the `capitalize` function.

2020-11-27 19:28 UTC, jerrylee17 approved these changes
Tested and it looks good to me!

2020-11-27 19:29 UTC, charlotte-zhuang approved these changes
Nice!

2020-11-27 19:31 UTC, merged